Repository fdietze/odor, pull requests merged in 2022-11, with the labels that each got.

#18 Update sbt to 1.7.3
  project/build.properties
Labels: dependencies, scala

#8 PostgresClient is tied to poolConnection
  .gitignore
  build.sbt
  odor/package.json
  odor/src/main/scala/PostgresClient.scala
  odor/src/test/scala/PgClientSpec.scala
Labels: ready-to-merge-squash, publish

#21 Update sbt-scalajs-bundler to 0.21.1
  project/plugins.sbt
Labels: dependencies, scala

#23 update ci build, yarn caching
  .github/workflows/build.yml
Labels: ready-to-merge-squash

#22 Disable pg-node type decoding
  odor/src/main/scala/PostgresClient.scala
Labels: ready-to-merge-squash, publish

#24 Update sbt-scalafmt to 2.5.0
  project/plugins.sbt
Labels: dependencies, scala

#26 Update sbt-scalajs, scalajs-compiler, ... to 1.12.0
  project/plugins.sbt
Labels: dependencies, scala
